server.port=${PORT:8080}

# MySQL on Railway
spring.datasource.url=jdbc:mysql://mainline.proxy.rlwy.net:19272/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=BgJSCHKyIOxYuhMdFWVIXaAuStUgWMBk
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# File uploads
file.upload-dir=./uploads

# Disable H2
spring.h2.console.enabled=false